[package]
name = "fercord"
version = "0.1.0"
edition = "2021"
include = [
    "src/*.rs",
    "**/*.md",
    "Cargo.toml"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.5"
config = { version = "0.13", default-features = false, features = ["toml"] }
serde = { version = "1", features = ["derive"]}
serde_json = "1"
tracing = "0.1"
tracing-subscriber = {version = "0.3", features = ["default", "env-filter"]}
chrono = "0.4"
chrono-tz = "0.8"
chrono-english = "0.1"
redis = { version = "0.22", features = ["tokio-comp", "json"] }
reqwest = { version = "0.11", features = ["stream", "rustls-tls"]}

[dependencies.tokio]
version = "1"
features = ["rt-multi-thread", "time"]

[dependencies.tokio-stream]
version = "0.1"

[dependencies.anyhow]
version = "1"
features = ["backtrace"]

[dependencies.sqlx]
version = "0.6"
features = ["chrono", "json", "postgres", "runtime-tokio-rustls", "migrate", "any", "offline"]

[dependencies.uuid]
version = "1.3.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde",             # Add serde support
]

# dev dependencies
[dev-dependencies]
tracing-test = "0.2"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1

# generated by 'cargo dist init'
[profile.dist]
inherits = "release"
debug = true
split-debuginfo = "packed"

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
