# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# rust-clippy is a tool that runs a bunch of lints to catch common
# mistakes in your Rust code and help improve your Rust code.
# More details at https://github.com/rust-lang/rust-clippy
# and https://rust-lang.github.io/rust-clippy/

name: Check PR

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
    types: [ready_for_review]

concurrency: "PR${{ github.event.pull_request && github.event.number }}"

jobs:
  is-changelog-updated:
    name: Check if updated changelogs are present
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: List changed files
        id: changed_files
        run: |
          git fetch origin ${{ github.event.pull_request.base.sha }}
          git diff --name-only ${{ github.event.pull_request.base.sha }} HEAD > changed_files.txt


  rust-clippy-analyze:
    name: Analyze with clippy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: taiki-e/install-action@cargo-binstall
      - name: Install required cargo
        run: cargo binstall -y --force clippy-sarif sarif-fmt

      - name: Run rust-clippy
        run:
          cargo clippy --message-format=json --locked | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true

  cargo-test:
    needs: rust-clippy-analyze
    name: Run unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run unit tests
        run: cargo test --tests --locked